# http://travis-ci.org/#!/Stub-O-Matic/python-client
language: python
python:
    - 2.7
  
install:
    - python setup.py install

# command to run tests
script: nosetests stubolib.tests.test_api
  

